### PR TITLE
Show marker metadata in Selection Info area

### LINKED ISSUE #138: Display selected marker metadata

### PR DESCRIPTION
**Pull request by vpzomtrrfrt**
Closes #138 

includes #147 for now to see what happens when that gets merged

### CODE REVIEW

**Comment by vpzomtrrfrt** [comment]
rebased, this should make sense now

**Review by PTLux1517 — APPROVED** [review]

**Comment by PTLux1517** [comment]
I'm not the best at CSS, but could we do something to this effect to increase the font size for just the output area and maintain uniform spacing around the first paragraph element:

```typescript
//add id to SelectionInfoView return
if(props.selectedMarkers.length === 0) return <div id={"selection-info-view"}><p>Nothing selected.</p></div>;
return <div id={"selection-info-view"}>
```

```scss
// ----------------------------------------- Grid Row 2 -----------------------------------------
#output-area {
   grid-row: 2;
   grid-column: 3;
   background-color: $outputAreaBGColor;
   padding: 5px;
   #selection-info-view {
      & > * {
         font-size: 9pt;
      }
      & :first-child {
         margin-top: 0;
      }
   }
}
```

**Comment by vpzomtrrfrt** [comment]
I think font sizes are currently too small everywhere

it might be worth changing the style for `p` in general to not have `margin-top`, that's what I'm used to since bootstrap does it

**Comment by PTLux1517** [comment]
We could change the universal font size, just be aware we'd have to keep the timeline table labels small for them to fit, as well as the loaded filenames and the soon-to-be-added loop playback checkbox (which you can see in my dev branch).

**Review by javitrejo14 — APPROVED** [review]

**Pull request merged**
